### ISSUE TITLE
Publish for SBT 1.0

### ISSUE THREAD

**Issue by nigredo-tori** [nrinaudo/sbt-glpages#1]
This plugin looks very useful, but it only exists for SBT 0.13. It shouldn't be too hard to set up cross-build for this and publish an artifact for newer SBT versions - or to simply switch to 1.0.

**Comment by nrinaudo** [comment]
Well, I _thought_ this would be a useful plugin, but then I started working with gitlab in earnest and discovered that it's entirely redundant. With the way gitlab-ci works, there really is no need for it.

I really should deprecate it...

**Comment by nigredo-tori** [comment]
Thank you. Indeed, I've delved slightly deeper into Gitlab documentation, and found that publishing to Pages is absurdly easy (as far as I understand).
1. Add a CI job called `pages` (name is important).
1. Make it build your site (static-only) in the `public` directory (name is important).
1. Expose this directory as an artifact.
1. You're done.

Why this is not the first thing I see on the [Pages documentation page](https://docs.gitlab.com/ee/user/project/pages/) is beyond me.
